def read_requirements(file_path):
    with open(file_path, 'r') as f:
        return set(line.strip() for line in f if line.strip() and not line.startswith('#'))

def compare_requirements(existing_reqs, used_reqs):
    return existing_reqs - used_reqs

if __name__ == "__main__":
    used_requirements = read_requirements('requirements.txt')  # Generated by pipreqs
    existing_requirements = read_requirements('existing_requirements.txt')  # Your current requirements.txt

    unnecessary_requirements = compare_requirements(existing_requirements, used_requirements)

    print("Packages listed in the existing requirements.txt but not used by the code:")
    for package in unnecessary_requirements:
        print(package)

